import type { Metadata } from "next"
import { Geist, Inter } from "next/font/google"
import "./globals.css"
import Header from "./conmponents/layout/Header"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${inter.variable} antialiased min-h-[125vh]`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
